
all:
	#g++ -Wall -Wextra -O3 main.cpp -lboost_filesystem -lboost_system -o cygfind.exe
	g++ -Wall -Wextra -O3 main.cpp -o cygfind.exe -lstdc++fs

msclang:
	clang++ -Wall -Wextra -O3 main.cpp -o msfind.exe
